linters:
  stylelint:
    config: 'stylelint.config.js'
    fixer: true
files:
  ignore:
    - 'normalize.css'
    - 'reboot.css'
    - 'reset.css'
    - '_framework.scss'
    - '_mixins.scss'
    - '_variables.scss'
    - 'style.css.map'
    
fixers:
  enable: true
